version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout
      - run: pip install -q vim-vint
      - run: sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe"
      - run: sudo apt-get update;sudo apt-get install -y shellcheck
      - run:
        name: Install
        command: ~/dotfiles/.bin/dotsinstall.sh install
      - run:
        name: Run vint
        command: test $(vint  ~/.vimrc ~/.vim/rc/* ~/.vim/rc/myplugins/* | grep -v "scriptencoding" | grep -v ".*\.nvim.*E492.*" | tee -a /dev/stderr | wc -l)  -le 1
      - run:
        name: Run shellcheck
        command: test $(shellcheck  -f gcc ~/.zshrc ~/.zsh/rc/* | grep -v "SC1009\|SC1036\|SC1056\|SC1070\|SC1072\|SC1073\|SC1083\|SC2034\|SC2139\|SC2148" | tee -a /dev/stderr | wc -l) -le 2
      - run:
        name: Run install plugin
        command: vim +PlugInstall +qall

