version: 2
jobs:
  build:
    working_directory: ~/Workspace
    docker:
      - image: node:6

        steps:
          - run:
            name: Trigger Jobs
            command: |
              function trigger_job() {
                job_name=$1
            curl --user ${CIRCLE_API_TOKEN}: \
            --data build_parameters[CIRCLE_JOB]=$job_name \
            --data revision=$CIRCLE_SHA1 \
            https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            }
            trigger_job build_ubuntu
            trigger_job build_centos

  build_ubuntu:
    working_directory: ~/dotfiles
    docker:
      - image: ubuntu:latest

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y git sudo software-properties-common
      - run: sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe"
      - run: sudo apt-get update;sudo apt-get install -y shellcheck
      - run: sudo apt-get install -y python-pip
      - run: pip install -q vim-vint
      - run: ~/dotfiles/.bin/dotsinstall.sh install
      - run: test $(vint  ~/.vimrc ~/.vim/rc/* ~/.vim/rc/myplugins/* | grep -v "scriptencoding" | grep -v ".*\.nvim.*E492.*" | tee -a /dev/stderr | wc -l)  -le 1
      - run: test $(shellcheck  -f gcc ~/.zshrc ~/.zsh/rc/* | grep -v "SC1009\|SC1036\|SC1056\|SC1070\|SC1072\|SC1073\|SC1083\|SC2034\|SC2139\|SC2148" | tee -a /dev/stderr | wc -l) -le 2
      - run: vim +PlugInstall +qall

  build_centos:
    working_directory: ~/dotfiles
    docker:
      - image: centos:latest

    steps:
      - checkout
      - run: yum check-update
      - run: yum install -y git sudo
      - run: ~/dotfiles/.bin/dotsinstall.sh install

